# Generated by Django 4.1.4 on 2023-01-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
